**Part A**

In [1]:
import numpy as np

In [2]:
#A.1 Matrix Multiplication(Resource Allocation)
Resources_Matrix = np.array([[100, 200],
                             [150, 250],
                             [120, 180]])

Allocation_Factors = np.array([[0.8, 1.2],
                               [1.0, 1.5]])

Result_Matrix = Resources_Matrix @ Allocation_Factors
print("A.1 Resulting Matrix:\n", Result_Matrix)

A.1 Resulting Matrix:
 [[280. 420.]
 [370. 555.]
 [276. 414.]]


In [3]:
# A.2 Element-wise Operations (Production Tracking)
Shift_A_Production = np.array([
    [10, 12, 11, 13, 14, 15, 16],
    [8, 9, 10, 11, 12, 12, 13],
    [14, 13, 15, 14, 13, 16, 15]
])

Shift_B_Production = np.array([
    [9, 10, 11, 10, 12, 14, 13],
    [7, 8, 9, 10, 11, 10, 12],
    [12, 13, 14, 13, 14, 15, 14]
])

Total_Production = Shift_A_Production + Shift_B_Production
print("\nA.2 Total Production:\n", Total_Production)


A.2 Total Production:
 [[19 22 22 23 26 29 29]
 [15 17 19 21 23 22 25]
 [26 26 29 27 27 31 29]]


In [4]:
# A.3 Activation Function (Sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

test_values = np.array([0, 1, -1, 2])
sigmoid_output = sigmoid(test_values)
print("\nA.3 Sigmoid Output:\n", sigmoid_output)


A.3 Sigmoid Output:
 [0.5        0.73105858 0.26894142 0.88079708]


In [5]:
# A.4 Gradient Calculation (Sigmoid derivative)
def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

gradient_output = sigmoid_derivative(test_values)
print("\nA.4 Sigmoid Gradient:\n", gradient_output)


A.4 Sigmoid Gradient:
 [0.25       0.19661193 0.19661193 0.10499359]


**Part C**

In [7]:
X = np.array([
    [20, 3, 4],
    [15, 5, 3],
    [30, 2, 2],
    [25, 4, 1],
    [35, 2, 3]
], dtype=float)

Y = np.array([[18], [20], [22], [25], [30]], dtype=float)

X = X / np.max(X, axis=0)
Y = Y / np.max(Y)

In [8]:
# Activation functions
def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(z):
    s = sigmoid(z)
    return s * (1 - s)

# Initialize weights
np.random.seed(42)
W1 = np.random.randn(3, 3) * 0.1
b1 = np.zeros((3, 1))
W2 = np.random.randn(1, 3) * 0.1
b2 = np.zeros((1, 1))

In [9]:
# Training parameters
lr = 0.1
epochs = 5000
m = X.shape[0]

# Training loop
for epoch in range(epochs):
    Z1 = X @ W1.T + b1.T
    A1 = relu(Z1)
    Z2 = A1 @ W2.T + b2
    A2 = sigmoid(Z2)

    loss = np.mean((A2 - Y) ** 2)

    dA2 = 2 * (A2 - Y) / m
    dZ2 = dA2 * sigmoid_derivative(Z2)
    dW2 = dZ2.T @ A1
    db2 = np.sum(dZ2, axis=0, keepdims=True).T
    dA1 = dZ2 @ W2
    dZ1 = dA1 * relu_derivative(Z1)
    dW1 = dZ1.T @ X
    db1 = np.sum(dZ1, axis=0, keepdims=True).T

    W1 -= lr * dW1
    b1 -= lr * db1
    W2 -= lr * dW2
    b2 -= lr * db2

    if epoch % 500 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

Epoch 0, Loss: 0.0916
Epoch 500, Loss: 0.0187
Epoch 1000, Loss: 0.0174
Epoch 1500, Loss: 0.0147
Epoch 2000, Loss: 0.0117
Epoch 2500, Loss: 0.0093
Epoch 3000, Loss: 0.0079
Epoch 3500, Loss: 0.0074
Epoch 4000, Loss: 0.0071
Epoch 4500, Loss: 0.0070


In [11]:
# Final results
print("\nFinal Weights and Biases:")
print("W1:", W1)
print("b1:", b1)
print("W2:", W2)
print("b2:", b2)

predictions = sigmoid(relu(X @ W1.T + b1.T) @ W2.T + b2)
print("\nPredictions (normalized):")
print(predictions)

predictions_orig = predictions * np.max(Y)
print("\nPredictions (original scale):")
print(predictions_orig)


Final Weights and Biases:
W1: [[ 1.033846   -0.29511935 -0.35254603]
 [ 0.66666602 -0.14722104 -0.24036718]
 [ 0.8770701  -0.12369175 -0.35389662]]
b1: [[-0.06112673]
 [-0.05239089]
 [-0.07343023]]
W2: [[1.13121527 0.71023489 0.94033248]]
b2: [[0.5595846]]

Predictions (normalized):
[[0.6363629 ]
 [0.63635642]
 [0.86132477]
 [0.81419367]
 [0.87580537]]

Predictions (original scale):
[[0.6363629 ]
 [0.63635642]
 [0.86132477]
 [0.81419367]
 [0.87580537]]
